// GENERATED by tools/gen_tasting_venues.py — DO NOT EDIT BY HAND.
// Source: sources/master_sources_catalog_120.json (cultural_domain=food-drink, entity_type=venue).
// Regenerate: python tools/gen_tasting_venues.py (a sync test enforces this stays current).
import type { TastingVenue } from "./venues";

export const TASTING_VENUES: TastingVenue[] = [
  { id: "rising_sun_vineyard", name: "Rising Sun Vineyard", kind: "winery", county: "bastrop", url: "https://www.risingsunvineyard.com/" },
  { id: "yegua_creek_brewery_restaurant", name: "Yegua Creek Brewery & Restaurant", kind: "brewery", county: "bastrop", url: "https://www.yeguacreekbrewery.com/events" },
  { id: "carter_creek_winery_resort_spa", name: "Carter Creek Winery Resort & Spa", kind: "winery", county: "blanco", url: "https://www.cartercreek.com/calendar-of-events" },
  { id: "garrison_brothers_distillery", name: "Garrison Brothers Distillery", kind: "distillery", county: "blanco", url: "https://www.garrisonbros.com/events" },
  { id: "iron_wolf_ranch_distillery", name: "Iron Wolf Ranch & Distillery", kind: "distillery", county: "burnet", url: "https://ironwolfranch.com/events/" },
  { id: "round_top_brewing_co", name: "Round Top Brewing Co.", kind: "brewery", county: "fayette", url: "http://www.roundtopbrewing.com/new-events-1" },
  { id: "bell_springs_winery", name: "Bell Springs Winery", kind: "winery", county: "hays", url: "https://www.bellsprings.co/events" },
  { id: "dripping_springs_distilling", name: "Dripping Springs Distilling", kind: "distillery", county: "hays", url: "https://drippingspringsdistilling.com/events/list/" },
  { id: "fitzhugh_brewing", name: "Fitzhugh Brewing", kind: "brewery", county: "hays", url: "https://www.fitzhughbrewing.com/upcoming-events" },
  { id: "treaty_oak_distilling", name: "Treaty Oak Distilling", kind: "distillery", county: "hays", url: "https://www.treatyoakdistilling.com/events" },
  { id: "vista_brewing", name: "Vista Brewing", kind: "brewery", county: "hays", url: "https://www.vistabrewingtx.com/calendars" },
  { id: "fall_creek_vineyards_tow", name: "Fall Creek Vineyards (Tow)", kind: "winery", county: "llano", url: "https://fcv.com/events/" },
  { id: "wedding_oak_winery", name: "Wedding Oak Winery", kind: "winery", county: "san saba", url: "http://www.weddingoakwinery.com/events" },
  { id: "austin_beerworks", name: "Austin Beerworks", kind: "brewery", county: "travis", url: "https://austinbeerworks.com/calendar" },
  { id: "central_machine_works_brewery", name: "Central Machine Works Brewery", kind: "brewery", county: "travis", url: "https://www.cmwbrewery.com/live-music" },
  { id: "jester_king_brewery", name: "Jester King Brewery", kind: "brewery", county: "travis", url: "https://jesterkingbrewery.com/events-calendar" },
  { id: "meanwhile_brewing_co", name: "Meanwhile Brewing Co.", kind: "brewery", county: "travis", url: "https://www.meanwhilebeer.com/events" },
  { id: "oasis_texas_brewing_company", name: "Oasis Texas Brewing Company", kind: "brewery", county: "travis", url: "https://www.otxbc.com/events" },
  { id: "still_austin_whiskey_co", name: "Still Austin Whiskey Co.", kind: "distillery", county: "travis", url: "https://www.stillaustin.com/tasting-room-events" },
  { id: "barking_armadillo_brewing", name: "Barking Armadillo Brewing", kind: "brewery", county: "williamson", url: "https://barkingarmadillo.com/" },
  { id: "rentsch_brewery", name: "Rentsch Brewery", kind: "brewery", county: "williamson", url: "https://rentschbrewery.com/" },
  { id: "whitestone_brewery", name: "Whitestone Brewery", kind: "brewery", county: "williamson", url: "https://whitestonebrewery.com/" },
];
