"""Tests for tools/visual_regression.py — the pixel-diff compare/decode
engine. Marked @pytest.mark.visual (auto-skipped by default, see
conftest.py); the decode/diff logic tested here needs NO browser or network
-- it's pure PNG-bytes-in-memory, generated by a tiny stdlib PNG encoder
defined in this file. What's NOT tested here (and can't be, in this
sandbox): capture_screenshot() against a real headless browser, since none
is installed -- that path is covered by an explicit, loudly-failing
missing-binary test instead of being skipped silently.
"""
import importlib.util
import pathlib
import struct
import sys
import zlib

import pytest

_PATH = pathlib.Path(__file__).resolve().parent.parent / "tools" / "visual_regression.py"
_spec = importlib.util.spec_from_file_location("visual_regression", _PATH)
vr = importlib.util.module_from_spec(_spec)
sys.modules["visual_regression"] = vr
_spec.loader.exec_module(vr)

pytestmark = pytest.mark.visual


def _encode_png(width, height, pixels_rgb: bytes) -> bytes:
    """Minimal stdlib PNG encoder (filter type 0, RGB, no interlace) — used
    only to generate in-memory test fixtures. Deliberately independent of
    vr.decode_png's implementation so a round-trip test is meaningful."""
    def chunk(ctype, data):
        return struct.pack(">I", len(data)) + ctype + data + struct.pack(">I", zlib.crc32(ctype + data))

    sig = b"\x89PNG\r\n\x1a\n"
    ihdr = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    raw = bytearray()
    stride = width * 3
    for row in range(height):
        raw.append(0)
        raw.extend(pixels_rgb[row * stride:(row + 1) * stride])
    idat = zlib.compress(bytes(raw), 9)
    return sig + chunk(b"IHDR", ihdr) + chunk(b"IDAT", idat) + chunk(b"IEND", b"")


def _solid(width, height, rgb) -> bytes:
    return bytes(rgb) * (width * height)


def _write(tmp_path, name, png_bytes) -> pathlib.Path:
    p = tmp_path / name
    p.write_bytes(png_bytes)
    return p


def test_decode_png_round_trips_solid_color(tmp_path):
    png = _encode_png(4, 4, _solid(4, 4, (255, 0, 0)))
    p = _write(tmp_path, "red.png", png)
    img = vr.decode_png(p)
    assert img.width == 4 and img.height == 4 and img.channels == 3
    assert img.pixels[:3] == bytes((255, 0, 0))
    assert len(img.pixels) == 4 * 4 * 3


def test_decode_png_rejects_bad_signature(tmp_path):
    p = _write(tmp_path, "notapng.png", b"not a real png file at all")
    with pytest.raises(vr.PngDecodeError, match="not a PNG file"):
        vr.decode_png(p)


def test_decode_png_accepts_str_path(tmp_path):
    png = _encode_png(2, 2, _solid(2, 2, (10, 20, 30)))
    p = _write(tmp_path, "small.png", png)
    img = vr.decode_png(str(p))  # str, not pathlib.Path — must not raise
    assert img.width == 2 and img.height == 2


def test_diff_identical_images_match():
    img1 = vr.Image(width=2, height=2, channels=3, pixels=_solid(2, 2, (100, 100, 100)))
    img2 = vr.Image(width=2, height=2, channels=3, pixels=_solid(2, 2, (100, 100, 100)))
    result = vr.diff_images(img1, img2, threshold=0.0)
    assert result.match is True
    assert result.differing_pixels == 0


def test_diff_completely_different_images_fails():
    img1 = vr.Image(width=2, height=2, channels=3, pixels=_solid(2, 2, (255, 0, 0)))
    img2 = vr.Image(width=2, height=2, channels=3, pixels=_solid(2, 2, (0, 0, 255)))
    result = vr.diff_images(img1, img2, threshold=0.01)
    assert result.match is False
    assert result.differing_pixels == 4
    assert result.fraction_diff == 1.0


def test_diff_tiny_noise_absorbed_by_tolerance():
    base_px = bytearray(_solid(2, 2, (255, 0, 0)))
    noisy_px = bytearray(base_px)
    noisy_px[0:3] = bytes((250, 3, 2))  # small per-channel delta, within default tolerance=8
    img1 = vr.Image(width=2, height=2, channels=3, pixels=bytes(base_px))
    img2 = vr.Image(width=2, height=2, channels=3, pixels=bytes(noisy_px))
    result = vr.diff_images(img1, img2, threshold=0.0)
    assert result.match is True
    assert result.differing_pixels == 0


def test_diff_one_real_pixel_change_exceeds_low_threshold_but_not_high():
    base_px = bytearray(_solid(4, 4, (255, 0, 0)))  # 16 pixels
    changed_px = bytearray(base_px)
    changed_px[0:3] = bytes((0, 255, 0))  # 1/16 = 6.25% of pixels totally different
    img1 = vr.Image(width=4, height=4, channels=3, pixels=bytes(base_px))
    img2 = vr.Image(width=4, height=4, channels=3, pixels=bytes(changed_px))

    low = vr.diff_images(img1, img2, threshold=0.01)
    assert low.match is False
    assert low.differing_pixels == 1

    high = vr.diff_images(img1, img2, threshold=0.10)
    assert high.match is True


def test_diff_dimension_mismatch_fails_loudly_not_silently():
    img1 = vr.Image(width=4, height=4, channels=3, pixels=_solid(4, 4, (1, 2, 3)))
    img2 = vr.Image(width=8, height=8, channels=3, pixels=_solid(8, 8, (1, 2, 3)))
    result = vr.diff_images(img1, img2, threshold=0.99)  # even a very loose threshold
    assert result.match is False  # dimension mismatch must never be "within threshold"
    assert "dimension mismatch" in result.reason


def test_compare_files_end_to_end(tmp_path):
    baseline = _write(tmp_path, "baseline.png", _encode_png(3, 3, _solid(3, 3, (10, 10, 10))))
    candidate = _write(tmp_path, "candidate.png", _encode_png(3, 3, _solid(3, 3, (10, 10, 10))))
    result = vr.compare_files(baseline, candidate, threshold=0.0)
    assert result.match is True


def test_cli_compare_exits_0_on_match(tmp_path, capsys):
    baseline = _write(tmp_path, "baseline.png", _encode_png(3, 3, _solid(3, 3, (10, 10, 10))))
    candidate = _write(tmp_path, "candidate.png", _encode_png(3, 3, _solid(3, 3, (10, 10, 10))))
    rc = vr.main(["compare", str(baseline), str(candidate)])
    out = capsys.readouterr().out
    assert rc == 0
    assert "MATCH" in out


def test_cli_compare_exits_1_on_diff(tmp_path, capsys):
    baseline = _write(tmp_path, "baseline.png", _encode_png(3, 3, _solid(3, 3, (10, 10, 10))))
    candidate = _write(tmp_path, "candidate.png", _encode_png(3, 3, _solid(3, 3, (200, 200, 200))))
    rc = vr.main(["compare", str(baseline), str(candidate), "--threshold", "0.0"])
    err = capsys.readouterr().err
    assert rc == 1
    assert "DIFF" in err


def test_capture_screenshot_fails_loudly_when_binary_missing(tmp_path):
    """This sandbox has no headless browser installed. Prove that the
    capture path fails LOUDLY with a clear message rather than silently
    producing a fake/blank screenshot — this is the honest, explicit
    coverage for the one thing this tool truly cannot exercise end-to-end
    here (see tests/visual_baselines/README.md)."""
    out_path = tmp_path / "shot.png"
    with pytest.raises(RuntimeError, match="not installed|not on PATH|is not installed/on PATH"):
        vr.capture_screenshot("definitely-not-a-real-browser-binary {url} {out}", "http://example.com", out_path)
    assert not out_path.exists()


def test_capture_screenshot_rejects_template_missing_placeholders(tmp_path):
    out_path = tmp_path / "shot.png"
    with pytest.raises(ValueError, match=r"\{url\}.*\{out\}"):
        vr.capture_screenshot("echo hello", "http://example.com", out_path)
