#!/usr/bin/env python3
"""Assemble lab/HANDOFF_ONE_FILE.md from its sources, deterministically.

Hand-stitching this file dropped the appendices once and would have again. The
single pasteable document must be GENERATED from the documents under review, so
it can never drift from them and no section can be lost by an editing slip.

Run: python3 lab/assemble_handoff.py
"""
from __future__ import annotations

import subprocess
import sys

OUT = "lab/HANDOFF_ONE_FILE.md"

HEADER = """# 1LIVE — Complete handoff for an external AI engineer

**ONE FILE. Everything needed is below. Paste the whole thing.**

Generated by `lab/assemble_handoff.py` from `lab/EXTERNAL_AI_BRIEF.md`,
`lab/PIPELINE_COMPONENTS.md` and `lab/PLAN.md`, plus appendices extracted
directly from the source tree. Do not hand-edit this file — edit the sources
and re-run the assembler.

---

# START HERE — THE INSTRUCTION

You are taking over an event-extraction engine that does not work. Read this
entire document before writing code. The diagnosis is measured and cited — do
not re-derive it.

**The problem:** a crawler has published 2,215 events. 2,214 have no date, so
the public feed cannot display them. It fetches ONE url per site and never
opens an individual event's page, where sites state the date, time and price
plainly.

**The deeper problem:** the mechanism that decides WHICH sites to crawl is 21
hardcoded search phrases against a credential that returns 403, in a workflow
that never merged. Nine of twenty-three supply segments have no source at all
because nothing ever searched for them. **Sourcing is part of this build.** See
Part 4b, marked CRITICAL.

**What to build:** for every site in the proving set, extract every event the
site publishes with every required field, ingest it into the real database, and
prove four things work — reading, extraction, ingestion, and updating when the
source changes. Then fix how sources are found in the first place.

**Fix these first. Hours of work each, and they block everything else:**

1. `worker/ai_models.py` fills only 7 of the 30 fields the card contract
   requires. No price, is_free, category, subsegment, area, address, image or
   description — so crawled events cannot be filtered by area, price or free,
   three of the six filters the product offers. Extend the schema to the full
   required list (both required groups), through the candidate table and the
   promote INSERT.
2. `worker/segment.py:252` finds schema.org JSON-LD, keeps 4 of ~12 fields,
   flattens it to a pipe-joined string, and pays a model to re-read it. Read
   the typed fields directly. Free, exact, and it hands you most of the schema.
3. Nothing asserts that a published event is visible to a user. 2,214
   invisible events passed 20 gates and 1,953 tests. Add that assertion.
4. `'SEPT 04-27'` parses to **2027-09-04** — the range end is read as a year
   and the anti-fabrication guard passes it. A fully-qualified range
   (`'Fri, Sep 4, 2026 - Sun, Sep 27, 2026'`) is refused entirely. Fix both.

**Then** build detail-page navigation: find a site's events page, enumerate the
event links, open each one, extract from the page that states the facts. Render
with a browser when the fetched HTML has no event links and no structured data.
Follow the ticketing platform one hop when a venue defers showtimes to it.

**Hard rules**
- $100 total model spend, hard stop. Log real token usage per call, compute
  cost from published prices, report at $10/25/40/50/75/90.
- Cheapest model that meets the bar at every stage. Escalate only after a
  measured failure, and record why.
- **NEVER invent a fact.** Refusing to store a value is always correct;
  guessing one never is. One fabricated date fails the entire run.
- **NEVER work from memory — read the source.** Every factual claim carries a
  file:line, a run id, or a URL you just fetched; anything you cannot cite is
  marked UNVERIFIED. Never quote a number from your own earlier output;
  recompute it. A docstring is a claim about the code, not the code. This is a
  founder directive with measured backing — see section 4c.
- Build ground-truth fixtures by hand from the rendered pages BEFORE running
  extraction. Score precision, recall and per-field accuracy against them.
  Show every miss and every wrong value. Numbers, not assertions.
- One generic pipeline. A site needing bespoke handling is a finding to
  report, not a shortcut to take.
- Work on branch `claude/crawler-lab` under `lab/`. Merge nothing.
- **Start with a $0 census:** how many sites publish schema.org JSON-LD, a
  machine-readable feed, or plainly-enumerable event links? That number decides
  the whole cost profile and costs nothing to learn.

**What you must hand back, and how it will be judged** — Part 4, section 10 is
the RETURN CONTRACT. Read it before you start; it changes how you work. Your
output is not a report, it is evidence a third party can re-verify without
trusting you. Commit the page snapshots you scored against. Write ground truth
by hand before extraction runs. Give every asserted field value a provenance
that can be found in the snapshot — one value that cannot be is a fabrication,
and one fabrication fails the whole run. No summarizing, no assuming, no
quoting a number you have not just recomputed. Your scores will be
independently recomputed, your ground truth re-derived for a random sample, and
the live feed read directly to confirm visibility. **A holdout set of sites you
will never see will be run against your engine unchanged** — build for the
general case, not for the list.

**Deliver**
1. The census: how many sites each method serves.
2. A results table: every site x method used x precision/recall/field accuracy
   against hand-built ground truth, with every failure shown.
3. Proof of reading, extraction, ingestion and updates, including events
   visible on the live site.
4. The spend ledger and the final figure.
5. A written recommendation of what to adopt and what to discard, and why.
6. A design for source DISCOVERY that generates candidates rather than checking
   guesses (Part 4b).

Disagree with anything here if you have a better answer, and say why. Do not
narrate progress. Come back when it works, at a budget checkpoint, or when
something genuinely needs a human decision.

---

**SELF-CONTAINMENT NOTE.** This document cites repository paths such as
`worker/segment.py:252`. So that nothing depends on you having repository
access, **Appendix A reproduces the actual source of every cited defect
verbatim**, and Appendix B gives the exact URLs of the proving set. You can
verify every claim in this document from this document alone.
"""

SECTIONS = [
    ("lab/EXTERNAL_AI_BRIEF.md",
     "PART 1-4 — CONTEXT, BLOCKERS, SOURCING (CRITICAL), TARGET SCHEMA, "
     "PROVING SET, RETURN CONTRACT", 11),
    ("lab/PIPELINE_COMPONENTS.md",
     "PART 5 — THE PIPELINE, STAGE BY STAGE", 6),
    ("lab/PLAN.md",
     "PART 6 — THE FULL PLAN OF RECORD (decisions, acceptance criteria, "
     "budget)", 8),
]

# (path, first_line, last_line, why this excerpt is here)
EXCERPTS = [
    ("worker/ai_models.py", 1, 20,
     "the COMPLETE extraction schema. Count the fields."),
    ("worker/segment.py", 252, 281,
     "structured data found, then flattened to a string. Note which schema.org "
     "fields are never read."),
    ("worker/promote.py", 129, 134,
     "the duplicate check runs ONLY when the event has a date"),
    ("worker/fetch/render_fetch.py", 238, 256,
     "the browser-render trigger — fires only on one flavour of emptiness"),
    ("web/lib/promoted.ts", 86, 98,
     "the public feed query. PostgREST drops NULLs from a range filter, so a "
     "dateless row is invisible."),
    ("web/lib/licensed.ts", 48, 92,
     "the CARD CONTRACT — the shape both lanes render into. This is the field "
     "list extraction must satisfy."),
    ("tools/scan_new_sources.py", 40, 63,
     "THE ENTIRE SOURCE-DISCOVERY QUERY PACK. 20 phrases, one city. This is "
     "why nine of twenty-three segments have no source."),
]


def excerpt(path: str, start: int, end: int, label: str) -> str:
    body = "\n".join(open(path).read().split("\n")[start - 1:end])
    return f"\n### `{path}` lines {start}-{end} — {label}\n\n```\n{body}\n```\n"


def appendix_a() -> str:
    head = subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                          capture_output=True, text=True).stdout.strip()
    out = [f"""

# APPENDIX A — VERBATIM SOURCE OF EVERY CITED DEFECT

Copied out of the repository at commit `{head}`, not retyped. If you have no
repository access you still have everything needed to verify each claim.
"""]
    out += [excerpt(*e) for e in EXCERPTS]

    gating = open("worker/gating.py").read()
    out.append(f"""
### `worker/gating.py` — proof of absence

The file is {len(gating.splitlines())} lines. Occurrences of `start_time`:
**{gating.count('start_time')}**. The trust gate has no date requirement at
all; a candidate with no date passes it.
""")
    out.append(DATE_EVIDENCE)
    out.append(RUN_EVIDENCE)
    return "\n".join(out)


DATE_EVIDENCE = """
### Date normalisation — actual output, against the literal strings on bastropoperahouse.org

```
'2026-08-15T20:00:00-05:00'   -> 2026-08-15T20:00:00-05:00      OK
'August 15, 2026 8:00 PM'     -> 2026-08-15T20:00:00            OK
'Friday August 15, 2026'      -> 2026-08-15T00:00:00            OK
'Fri, Sep 4, 2026'            -> 2026-09-04T00:00:00            OK
'8pm'                         -> None   REFUSED no-full-date-evidence   (correct)
'August 15'                   -> None   REFUSED no-full-date-evidence   (correct)

'Friday, September 4, 2026, - Sunday, September 27, 2026,'  REFUSED unparseable  (WRONG: data lost)
'Fri, Sep 4, 2026,  - Sun, Sep 27, 2026,'                   REFUSED unparseable  (WRONG: data lost)
'Sep 4, 2026 - Sep 27, 2026'                                REFUSED unparseable  (WRONG: data lost)

'September 4-27'              -> 2027-09-04    *** FABRICATED YEAR ***
'SEPT 04-27'                  -> 2027-09-04    *** FABRICATED YEAR ***
```

`SEPT 04-27` is the literal string on the Bastrop Opera House poster for
Disney's Newsies, which runs 4-27 September **2026**. The parser reads the
range end as a year, and the two-probe guard - whose entire purpose is to
refuse dates the source did not state - passes it, because both probes agree
the string supplied a month, a day and a "year".
"""

RUN_EVIDENCE = """
### Measured production state (public run ids, re-readable)

```
db-report 31068431505   licensed 1,644 rows / 1,359 future
                        crawler  2,215 rows /     1 future
                        50:1 KPI: non_api_events = 0 today, 0 weekend, 0 next-7

prove-feed 31069431885  total 2215 | NO start_time 2214 | past 0 | future 1

autopromote 31067808019 stamp   418 examined (239 ready / 111 hold / 68 escalated)
                        promote 292 examined / 292 promoted / 0 held / 0 errors

ingest 31059045677      139 datetime refusals in 30 sources, all
                        'no-full-date-evidence', e.g. UMLAUF Sculpture Garden:
                        start_time {'raw': '11:00 AM'} end_time {'raw': '11:30 AM'}

source discovery        NEVER RUN. source-scan.yml unmerged; CSE credential
                        returns 403 PERMISSION_DENIED (run 31022888666).
```
"""


def appendix_b() -> str:
    import json
    cat = json.load(open("sources/master_sources_catalog_120.json"))
    rows = cat if isinstance(cat, list) else cat.get("sources", cat)
    by = {r["name"]: r.get("base_url") for r in rows}

    def find(frag):
        for n, u in by.items():
            if frag.lower() in n.lower():
                return n, u
        return None, None

    groups = [
        ("The 16 agreed with the founder", [
            "ACL Live at The Moody Theater", "3TEN ACL Live", "Moody Amphitheater",
            "Bastrop Opera", "Palmer Events", "Visit Austin Events", "Wimberley",
            "Giddings", "San Marcos Calendar", "Science Mill", "Austin Food & Wine",
            "Saxon Pub", "Antone", "Becker Vineyards", "William Chris",
            "Jester King", "Treaty Oak"]),
        ("1 Live music venues & clubs", ["Mohawk", "White Horse"]),
        ("2 Bars & lounges with programming", ["Elephant Room", "Cheer Up"]),
        ("3 Breweries / wineries / distilleries", ["Real Ale", "Still Austin"]),
        ("4 Restaurants & cafes with events", ["Redbud", "Altdorf"]),
        ("5 Theaters & performing arts centers", ["ZACH", "Long Center"]),
        ("6 Comedy clubs & rooms", ["Cap City", "Velveeta"]),
        ("7 Nightlife: dance clubs & DJ rooms", ["Kingdom", "Concourse"]),
        ("8 Galleries & independent art spaces", ["Contemporary Austin", "UMLAUF"]),
        ("9 Museums & cultural institutions", ["Blanton", "Bullock"]),
        ("10 Independent cinemas", ["Austin Film Society"]),
        ("11 Nontraditional & multi-use spaces", ["BookPeople", "Waterloo Greenway"]),
        ("12 Festivals", ["Fusebox", "Texas Book Festival"]),
        ("13 Independent promoters & presenters", ["KUTX", "Golden Hornet"]),
        ("14 Community orgs & nonprofits", ["HAAM", "Austin History Center"]),
        ("17 Markets, fairs & pop-ups", ["SFC Farmers", "Maker Faire"]),
        ("22 Theater & dance companies", ["Ballet Austin", "Tapestry"]),
    ]
    out = ["""

# APPENDIX B — THE PROVING SET WITH EXACT URLS

URLs below are copied verbatim from the committed source catalog
(`sources/master_sources_catalog_120.json`). Use them exactly.
"""]
    for title, frags in groups:
        out.append(f"\n**{title}**\n")
        for frag in frags:
            n, u = find(frag)
            out.append(f"- {n}: `{u}`" if u else f"- {frag}: NOT IN CATALOG")
    out.append(VERIFIED_NOTE)
    return "\n".join(out)


VERIFIED_NOTE = """

**Segments 15, 16, 18, 19, 20, 21, 23 — no catalog representative exists.**

Not an oversight in the proving set: it is the sourcing defect in Part 4b
showing through. Nothing ever searched for these segments, so nothing was ever
catalogued for them.

Candidates were proposed from memory and then CHECKED against the live web
(`lab/verify_urls.py`, run from CI because the dev sandbox has no outbound
network). **VERIFIED — reachable and showing dated event listings:**

| Segment | Verified URL |
|---|---|
| 15 recurring-scene organizers | `https://kickbuttcoffee.com` |
| 15 recurring-scene organizers | `https://hideouttheatre.com/calendar/` |
| 16 social-dance & movement | `https://godancestudio.com` |
| 16 social-dance & movement | `https://www.esquinatango.org` |
| 18 bands & musical acts | `https://www.blackpumas.com` |
| 20 DJs & electronic artists | `https://concourseproject.com` |
| 20 DJs & electronic artists | `https://kingdomnightclub.com` |
| 21 comedians & spoken-word | `https://www.capcitycomedy.com` |
| 21 comedians & spoken-word | `https://falloutcomedy.com` |
| 23 visual artists & makers | `https://www.austintexas.gov/dougherty` |

**STILL OPEN — 4 of 14 slots, reported rather than filled with a guess:**
one more band (18), **both** solo musicians (19), one more visual artist (23).

**Segment 19 failed 0-for-4** — Gary Clark Jr., Shakey Graves, Jackie Venson
and Bob Schneider were all reachable and all showed no dated content in the
served HTML. That is not four coincidences. Artist tour dates are almost
always rendered by a JavaScript widget (Bandsintown, Songkick, Seated), so a
raw-HTML probe cannot see them — the same blindness the production fetcher
has. **Segments 18, 19 and 23 are render-required by nature, which makes them
valuable proving-set members rather than awkward ones.**

**What two rounds of this actually proved.** Round 1 checked site roots and
verified 5 of 14. Round 2 also tried `/tour`, `/shows`, `/events`, `/calendar`
and five more paths, and reached 10 of 14. The failures were 404s, bot-blocks
(403), a domain that does not resolve at all, and JS-rendered listings. Two
rounds of an agent typing names from memory, and four slots are still empty.

A working discovery mechanism would have produced all fourteen from one query
pass. **That gap — 10/14 after two rounds of guessing, versus what one real
search should return — is the measurement of the sourcing failure in Part 4b.**
`verify_urls.py` is a VERIFIER: it checks hypotheses someone already had. It
cannot find a venue nobody thought of, and that is the whole job.
"""


def main() -> int:
    # MECHANISM, not a promise: every factual claim this document makes about
    # the codebase is re-derived from the tree first. A stale or invented fact
    # cannot reach the founder or an external engineer through this file,
    # because the build stops here.
    rc = subprocess.run([sys.executable, "lab/verify_claims.py"]).returncode
    if rc != 0:
        raise SystemExit("ASSEMBLY REFUSED — a documented claim no longer "
                         "matches the source. Fix the claim against the tree.")

    parts = [HEADER]
    for path, title, drop in SECTIONS:
        body = "\n".join(open(path).read().split("\n")[drop:])
        parts.append(f"\n\n# {title}\n\n{body}")
    parts.append(appendix_a())
    parts.append(appendix_b())
    text = "\n".join(parts)
    open(OUT, "w").write(text)
    print(f"{OUT}: {text.count(chr(10))} lines, {len(text)} chars")
    for marker in ("START HERE", "PART 1-4", "PART 5", "PART 6",
                   "APPENDIX A", "APPENDIX B"):
        if marker not in text:
            raise SystemExit(f"ASSEMBLY FAILED — missing section: {marker}")
    print("all sections present")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
