#!/usr/bin/env python3
"""Assemble lab/HANDOFF_ONE_FILE.md from its sources, deterministically.

Hand-stitching this file dropped the appendices once and would have again. The
single pasteable document must be GENERATED from the documents under review, so
it can never drift from them and no section can be lost by an editing slip.

Run: python3 lab/assemble_handoff.py
"""
from __future__ import annotations

import subprocess
import sys

OUT = "lab/HANDOFF_ONE_FILE.md"

HEADER = """# 1LIVE — Complete handoff for an external AI engineer

**ONE FILE. Everything needed is below. Paste the whole thing.**

Generated by `lab/assemble_handoff.py` from `lab/EXTERNAL_AI_BRIEF.md`,
`lab/PIPELINE_COMPONENTS.md` and `lab/PLAN.md`, plus appendices extracted from
the source tree. Do not hand-edit — edit the sources and re-run the assembler,
which refuses to build if any documented claim no longer matches the code.

---

# THE ASSIGNMENT

## What this is

An event-discovery product for Austin and the Texas Hill Country. It crawls
venue, festival, civic and producer websites, extracts the events they publish,
passes them through a verification gate, and shows the survivors on a public
feed. The site is live behind a stealth gate. A licensed lane (Ticketmaster and
similar) works fine and is not your problem.

## What is wrong, measured

2,215 events have been published by the crawler. **2,214 have no date**, so the
feed cannot display them. Every one passed a trust gate and is labelled
`confirmed`. The licensed lane, by contrast, has 1,359 events with usable
dates. Run ids and counts are in Appendix A.

Two causes, both structural:

1. **The crawler never clicks through.** It fetches ONE url per site and
   extracts from that page. It never finds a site's events section, never opens
   an individual event page, never follows a ticketing link. Meanwhile the
   event pages state everything plainly.
2. **The mechanism that decides WHICH sites to crawl is 20 hardcoded search
   phrases** against a credential that returns 403, in a workflow that never
   merged. Nine of twenty-three supply segments have no source at all because
   nothing ever searched for them. See Part 4b, marked CRITICAL.

## What done means

For every site in the proving set: extract **every event the site publishes**,
with **every required field** (Part 3a — both required groups, not a subset),
ingest it into the real database, and prove all four stages work — reading,
extraction, ingestion, and updating when the source changes. Then fix how
sources are found in the first place.

Field completeness is not "title and date". It is date, start time, end time,
venue, address, area, category, subsegment, price, free/paid, ticket url,
description, image, performer, door time, age restriction, on-sale status,
**cancellation status**, organizer, geo, series, and any specials the venue
states. A listing without those is a calendar entry, not a guide.

---

# HOW — the baseline approach

This is the approach to beat. **You may replace it; see "YOUR ALTERNATIVE"
below.** What you may not do is skip the measurements.

## Step 0 — the $0 census, before any design decision

Run `lab/census_structured.py` (already written) from CI. It reports, per site:
schema.org JSON-LD Event objects, microdata, machine feeds, enumerable event
links, or nothing-in-the-markup. It also counts which card fields each site's
JSON-LD already carries.

**This number governs everything downstream.** Do not choose an architecture
before you have it. It costs nothing.

## Step 1 — fix what is cheap and blocking

1. **Stop destroying structured data.** `worker/segment.py:252` finds the
   schema.org Event object, keeps 4 of ~12 fields, flattens it to a
   pipe-joined string, and pays a model to re-read it. Read the typed fields
   directly. Free, exact, cannot hallucinate, and it hands you most of the
   required schema. Engineering record with measured effort, cascade and
   go/no-go: `lab/FIX_01_JSONLD.md`.
2. **Extend the extraction schema.** `worker/ai_models.py` holds 11 fields; the
   card contract holds 30. Note the sequencing constraint: that file is inside
   `HARNESS_MANIFEST`, so changing it takes extraction offline until a
   founder-attended exam re-certifies. Plan around it.
3. **Add a visibility assertion.** Nothing anywhere checks that a published
   event is visible to a user. 2,214 invisible events passed 20 gates and 1,953
   tests. This test is the reason none of it was caught.
4. **Fix the fabricated year.** `'SEPT 04-27'` normalises to **2027-09-04** —
   the range end read as a year, waved through by the guard whose sole purpose
   is refusing dates the source never stated. A fully-qualified range is
   refused outright, losing every theatre run and festival.

## Step 2 — build navigation

Find a site's events page. Enumerate individual event links. Open each one.
Extract from the page that states the facts. Render with a browser when the
served HTML has no event links and no structured data. Follow the ticketing
platform one hop when a venue defers showtimes to it (Ludus, Tixr, Eventbrite,
See Tickets, Prekindle).

## Step 3 — rebuild discovery

Generate candidates instead of checking guesses. `lab/discover_sources.py` is a
working first method — it mines the aggregators the pipeline already fetches
for outbound links to venues the catalog has never seen, ranks by how many
independent guides link each one, and qualifies the survivors. No credential,
no model call. Extend it: link-graph expansion, directory mining, ticketing-
platform enumeration, sitemaps, performer-to-venue reverse lookup.

## Step 4 — prove it, per the RETURN CONTRACT in Part 4 section 10

Snapshots committed. Ground truth hand-written BEFORE extraction. Every
asserted value carrying a provenance findable in the snapshot. Scores computed,
not asserted. A live read-back from the public feed.

---

# REVIEW FIX 01 AND COMMENT — a required deliverable

Part 7 is a complete engineering record for one defect: the destruction of
structured event data at `worker/segment.py:252`. It runs problem → severity →
cascade → measured effort → plan → testing → go/no-go/delay → proof. **Nothing
in it has been built. It is awaiting a GO decision, and your evaluation is an
input to that decision.**

Review it adversarially and answer each of these in writing:

1. **Is the severity right?** It is rated CRITICAL on three grounds —
   correctness, cost, coverage. Argue it up or down.
2. **Is the cascade complete or overstated?** It traces dropped fields to
   priceless cards, two dead filters, and cancelled shows published as live.
   Name any link that does not hold, and any consequence it missed.
3. **Is the effort measurement sound?** Every number was read from the tree —
   one production caller, the `List[str]` contract, 11 + 9 tests, 2
   monkeypatches, membership of the 27-file arming closure, and
   `HARNESS_MANIFEST` membership. Check the method, not just the numbers. If a
   count is wrong, say which and how you derived yours.
4. **Is the phase split correct?** It claims Phase 1 ships with extraction
   running because `segment.py` is outside the manifest, while Phase 2 takes
   extraction offline because `ai_models.py` is inside it. That constraint
   drives the whole sequencing. Verify it.
5. **Is the additive design the right call**, or should `segment_events` change
   contract outright and take the test churn?
6. **Are the go/no-go thresholds right?** GO at ≥30% structured coverage with
   ≥95% field recall, DELAY at 10-30%, NO-GO under 10%. Are those the right
   numbers, and is any of them gameable as written?
7. **Is the proof list sufficient?** Seven items. Which would you add, and
   which is theatre?
8. **What is missing entirely?**

Give a verdict: **GO**, **NO-GO**, or **DELAY**, with reasons. You are not
bound by the founder's decision and the founder is not bound by yours — but an
argued disagreement is more useful than agreement, and it is wanted.

---

# YOUR ALTERNATIVE — deliberately invited

The approach above is a considered baseline, not a cage. **If you have a better
architecture, build it and say why.** Explicitly welcome: a different tier
order, a single-pass renderer for everything, an LLM-vision approach over
rendered screenshots, a headless-browser-first design, a per-platform adapter
registry, a different identity model for runs and performances, or something
not listed.

An alternative must satisfy the same bar, and this is the only thing that is
non-negotiable:

1. It is measured on the same proving set, against the same hand-built ground
   truth, at the same thresholds (Part 3a, Part 4 §7).
2. It costs less than $100 in model spend and the ledger proves it.
3. It generalises — a holdout set you never see will be run against it.
4. It never asserts a fact the source did not state.
5. You state plainly what it does worse than the baseline, not only what it
   does better.

If your alternative wins on the numbers, it is the recommendation. If it loses,
say so — a negative result honestly reported is worth more than a positive one
that does not survive re-scoring.

---

# HARD RULES

- **$100 total model spend, hard stop.** Log real token usage per call to
  `lab/spend.jsonl`, compute cost from published prices, report at
  $10/25/40/50/75/90. Target under $25.
- **Cheapest model that meets the bar at every stage.** Escalate a specific
  site only after a measured failure, and record why.
- **NEVER invent a fact.** Refusing to store a value is always correct; guessing
  one never is. One fabricated date fails the entire run.
- **NEVER WORK FROM MEMORY — read the source.** Every factual claim carries a
  file:line, a run id, or a URL you just fetched; anything you cannot cite is
  marked UNVERIFIED. Never quote a number from your own earlier output;
  recompute it. A docstring is a claim about the code, not the code. Mechanism,
  not a promise: `lab/verify_claims.py` re-derives every documented claim from
  the tree and the doc build fails if one drifts. It caught three wrong claims
  on its first run.
- **Capability is not action.** "This could be verified" is not a result.
  Verify it.
- **Every defect writeup follows the standing shape:** problem, severity and
  why, the full cascade, effort MEASURED not guessed, plan including testing,
  numeric go/no-go/delay set before the data exists, then indisputable proof.
  Template: `lab/FIX_01_JSONLD.md`.
- **One generic pipeline.** A site needing bespoke handling is a finding to
  report, not a shortcut to take.
- **Work on branch `claude/crawler-lab` under `lab/`. Merge nothing.**
- **Nothing ends in "unable to".** Part 0 lists every blocked route with its
  workaround. If you find one without a route, report it as a defect in this
  document and take the nearest route that works.

---

# WHAT TO DELIVER

1. The census: how many sites each tier serves, and which card fields arrive
   free from structured data.
2. A results table: every site x method used x precision/recall/per-field
   accuracy against hand-built ground truth, with every miss and wrong value
   shown.
3. Proof of all four stages — reading, extraction, ingestion, updates —
   including events visible on the live site.
4. The spend ledger and the final figure.
5. A recommendation of what to adopt and what to discard, each claim citing an
   artifact.
6. A discovery design that generates candidates rather than checking guesses.
7. If you took an alternative approach: the comparison, including where it is
   worse.
8. Your review of Fix 01 (Part 7) — all eight questions answered, with a
   GO / NO-GO / DELAY verdict and reasons.

Do not narrate progress. Come back when it works, at a budget checkpoint, or
when something genuinely needs a human decision — money, legal, credentials,
or a change to what counts as verified.

---

**SELF-CONTAINMENT.** This document cites repository paths. Appendix A
reproduces the actual source of every cited defect verbatim and Appendix B
gives the proving set's exact URLs, so every claim here is verifiable from this
document alone, with or without repository access.
"""

SECTIONS = [
    ("lab/EXTERNAL_AI_BRIEF.md",
     "PART 1-4 — CONTEXT, BLOCKERS, SOURCING (CRITICAL), TARGET SCHEMA, "
     "PROVING SET, RETURN CONTRACT", 11),
    ("lab/PIPELINE_COMPONENTS.md",
     "PART 5 — THE PIPELINE, STAGE BY STAGE", 6),
    ("lab/PLAN.md",
     "PART 6 — THE FULL PLAN OF RECORD (decisions, acceptance criteria, "
     "budget)", 8),
    ("lab/FIX_01_JSONLD.md",
     "PART 7 — FIX 01 ENGINEERING RECORD — REVIEW THIS AND COMMENT", 0),
]

# (path, first_line, last_line, why this excerpt is here)
EXCERPTS = [
    ("worker/ai_models.py", 1, 20,
     "the COMPLETE extraction schema. Count the fields."),
    ("worker/segment.py", 252, 281,
     "structured data found, then flattened to a string. Note which schema.org "
     "fields are never read."),
    ("worker/promote.py", 129, 134,
     "the duplicate check runs ONLY when the event has a date"),
    ("worker/fetch/render_fetch.py", 238, 256,
     "the browser-render trigger — fires only on one flavour of emptiness"),
    ("web/lib/promoted.ts", 86, 98,
     "the public feed query. PostgREST drops NULLs from a range filter, so a "
     "dateless row is invisible."),
    ("web/lib/licensed.ts", 48, 92,
     "the CARD CONTRACT — the shape both lanes render into. This is the field "
     "list extraction must satisfy."),
    ("tools/scan_new_sources.py", 40, 63,
     "THE ENTIRE SOURCE-DISCOVERY QUERY PACK. 20 phrases, one city. This is "
     "why nine of twenty-three segments have no source."),
]


def excerpt(path: str, start: int, end: int, label: str) -> str:
    body = "\n".join(open(path).read().split("\n")[start - 1:end])
    return f"\n### `{path}` lines {start}-{end} — {label}\n\n```\n{body}\n```\n"


def appendix_a() -> str:
    head = subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                          capture_output=True, text=True).stdout.strip()
    out = [f"""

# APPENDIX A — VERBATIM SOURCE OF EVERY CITED DEFECT

Copied out of the repository at commit `{head}`, not retyped. If you have no
repository access you still have everything needed to verify each claim.
"""]
    out += [excerpt(*e) for e in EXCERPTS]

    gating = open("worker/gating.py").read()
    out.append(f"""
### `worker/gating.py` — proof of absence

The file is {len(gating.splitlines())} lines. Occurrences of `start_time`:
**{gating.count('start_time')}**. The trust gate has no date requirement at
all; a candidate with no date passes it.
""")
    out.append(DATE_EVIDENCE)
    out.append(RUN_EVIDENCE)
    return "\n".join(out)


DATE_EVIDENCE = """
### Date normalisation — actual output, against the literal strings on bastropoperahouse.org

```
'2026-08-15T20:00:00-05:00'   -> 2026-08-15T20:00:00-05:00      OK
'August 15, 2026 8:00 PM'     -> 2026-08-15T20:00:00            OK
'Friday August 15, 2026'      -> 2026-08-15T00:00:00            OK
'Fri, Sep 4, 2026'            -> 2026-09-04T00:00:00            OK
'8pm'                         -> None   REFUSED no-full-date-evidence   (correct)
'August 15'                   -> None   REFUSED no-full-date-evidence   (correct)

'Friday, September 4, 2026, - Sunday, September 27, 2026,'  REFUSED unparseable  (WRONG: data lost)
'Fri, Sep 4, 2026,  - Sun, Sep 27, 2026,'                   REFUSED unparseable  (WRONG: data lost)
'Sep 4, 2026 - Sep 27, 2026'                                REFUSED unparseable  (WRONG: data lost)

'September 4-27'              -> 2027-09-04    *** FABRICATED YEAR ***
'SEPT 04-27'                  -> 2027-09-04    *** FABRICATED YEAR ***
```

`SEPT 04-27` is the literal string on the Bastrop Opera House poster for
Disney's Newsies, which runs 4-27 September **2026**. The parser reads the
range end as a year, and the two-probe guard - whose entire purpose is to
refuse dates the source did not state - passes it, because both probes agree
the string supplied a month, a day and a "year".
"""

RUN_EVIDENCE = """
### Measured production state (public run ids, re-readable)

```
db-report 31068431505   licensed 1,644 rows / 1,359 future
                        crawler  2,215 rows /     1 future
                        50:1 KPI: non_api_events = 0 today, 0 weekend, 0 next-7

prove-feed 31069431885  total 2215 | NO start_time 2214 | past 0 | future 1

autopromote 31067808019 stamp   418 examined (239 ready / 111 hold / 68 escalated)
                        promote 292 examined / 292 promoted / 0 held / 0 errors

ingest 31059045677      139 datetime refusals in 30 sources, all
                        'no-full-date-evidence', e.g. UMLAUF Sculpture Garden:
                        start_time {'raw': '11:00 AM'} end_time {'raw': '11:30 AM'}

source discovery        NEVER RUN. source-scan.yml unmerged; CSE credential
                        returns 403 PERMISSION_DENIED (run 31022888666).
```
"""


def appendix_b() -> str:
    import json
    cat = json.load(open("sources/master_sources_catalog_120.json"))
    rows = cat if isinstance(cat, list) else cat.get("sources", cat)
    by = {r["name"]: r.get("base_url") for r in rows}

    def find(frag):
        for n, u in by.items():
            if frag.lower() in n.lower():
                return n, u
        return None, None

    groups = [
        ("The 16 agreed with the founder", [
            "ACL Live at The Moody Theater", "3TEN ACL Live", "Moody Amphitheater",
            "Bastrop Opera", "Palmer Events", "Visit Austin Events", "Wimberley",
            "Giddings", "San Marcos Calendar", "Science Mill", "Austin Food & Wine",
            "Saxon Pub", "Antone", "Becker Vineyards", "William Chris",
            "Jester King", "Treaty Oak"]),
        ("1 Live music venues & clubs", ["Mohawk", "White Horse"]),
        ("2 Bars & lounges with programming", ["Elephant Room", "Cheer Up"]),
        ("3 Breweries / wineries / distilleries", ["Real Ale", "Still Austin"]),
        ("4 Restaurants & cafes with events", ["Redbud", "Altdorf"]),
        ("5 Theaters & performing arts centers", ["ZACH", "Long Center"]),
        ("6 Comedy clubs & rooms", ["Cap City", "Velveeta"]),
        ("7 Nightlife: dance clubs & DJ rooms", ["Kingdom", "Concourse"]),
        ("8 Galleries & independent art spaces", ["Contemporary Austin", "UMLAUF"]),
        ("9 Museums & cultural institutions", ["Blanton", "Bullock"]),
        ("10 Independent cinemas", ["Austin Film Society"]),
        ("11 Nontraditional & multi-use spaces", ["BookPeople", "Waterloo Greenway"]),
        ("12 Festivals", ["Fusebox", "Texas Book Festival"]),
        ("13 Independent promoters & presenters", ["KUTX", "Golden Hornet"]),
        ("14 Community orgs & nonprofits", ["HAAM", "Austin History Center"]),
        ("17 Markets, fairs & pop-ups", ["SFC Farmers", "Maker Faire"]),
        ("22 Theater & dance companies", ["Ballet Austin", "Tapestry"]),
    ]
    out = ["""

# APPENDIX B — THE PROVING SET WITH EXACT URLS

URLs below are copied verbatim from the committed source catalog
(`sources/master_sources_catalog_120.json`). Use them exactly.
"""]
    for title, frags in groups:
        out.append(f"\n**{title}**\n")
        for frag in frags:
            n, u = find(frag)
            out.append(f"- {n}: `{u}`" if u else f"- {frag}: NOT IN CATALOG")
    out.append(VERIFIED_NOTE)
    return "\n".join(out)


VERIFIED_NOTE = """

**Segments 15, 16, 18, 19, 20, 21, 23 — no catalog representative exists.**

Not an oversight in the proving set: it is the sourcing defect in Part 4b
showing through. Nothing ever searched for these segments, so nothing was ever
catalogued for them.

Candidates were proposed from memory and then CHECKED against the live web
(`lab/verify_urls.py`, run from CI because the dev sandbox has no outbound
network). **VERIFIED — reachable and showing dated event listings:**

| Segment | Verified URL |
|---|---|
| 15 recurring-scene organizers | `https://kickbuttcoffee.com` |
| 15 recurring-scene organizers | `https://hideouttheatre.com/calendar/` |
| 16 social-dance & movement | `https://godancestudio.com` |
| 16 social-dance & movement | `https://www.esquinatango.org` |
| 18 bands & musical acts | `https://www.blackpumas.com` |
| 20 DJs & electronic artists | `https://concourseproject.com` |
| 20 DJs & electronic artists | `https://kingdomnightclub.com` |
| 21 comedians & spoken-word | `https://www.capcitycomedy.com` |
| 21 comedians & spoken-word | `https://falloutcomedy.com` |
| 23 visual artists & makers | `https://www.austintexas.gov/dougherty` |

**STILL OPEN — 4 of 14 slots, reported rather than filled with a guess:**
one more band (18), **both** solo musicians (19), one more visual artist (23).

**Segment 19 failed 0-for-4** — Gary Clark Jr., Shakey Graves, Jackie Venson
and Bob Schneider were all reachable and all showed no dated content in the
served HTML. That is not four coincidences. Artist tour dates are almost
always rendered by a JavaScript widget (Bandsintown, Songkick, Seated), so a
raw-HTML probe cannot see them — the same blindness the production fetcher
has. **Segments 18, 19 and 23 are render-required by nature, which makes them
valuable proving-set members rather than awkward ones.**

**What two rounds of this actually proved.** Round 1 checked site roots and
verified 5 of 14. Round 2 also tried `/tour`, `/shows`, `/events`, `/calendar`
and five more paths, and reached 10 of 14. The failures were 404s, bot-blocks
(403), a domain that does not resolve at all, and JS-rendered listings. Two
rounds of an agent typing names from memory, and four slots are still empty.

A working discovery mechanism would have produced all fourteen from one query
pass. **That gap — 10/14 after two rounds of guessing, versus what one real
search should return — is the measurement of the sourcing failure in Part 4b.**
`verify_urls.py` is a VERIFIER: it checks hypotheses someone already had. It
cannot find a venue nobody thought of, and that is the whole job.
"""


def main() -> int:
    # MECHANISM, not a promise: every factual claim this document makes about
    # the codebase is re-derived from the tree first. A stale or invented fact
    # cannot reach the founder or an external engineer through this file,
    # because the build stops here.
    rc = subprocess.run([sys.executable, "lab/verify_claims.py"]).returncode
    if rc != 0:
        raise SystemExit("ASSEMBLY REFUSED — a documented claim no longer "
                         "matches the source. Fix the claim against the tree.")

    # Directive D2 — "Can does not mean do or must or will." An offer to
    # perform a verification, standing in for the verification, cannot reach
    # the founder through this document.
    rc = subprocess.run([sys.executable, "lab/capability_lint.py"]).returncode
    if rc != 0:
        raise SystemExit("ASSEMBLY REFUSED — an unexecuted capability claim. "
                         "Do the thing, or mark it [NOT DONE: <reason>].")

    parts = [HEADER]
    for path, title, drop in SECTIONS:
        body = "\n".join(open(path).read().split("\n")[drop:])
        parts.append(f"\n\n# {title}\n\n{body}")
    parts.append(appendix_a())
    parts.append(appendix_b())
    text = "\n".join(parts)
    open(OUT, "w").write(text)
    print(f"{OUT}: {text.count(chr(10))} lines, {len(text)} chars")
    for marker in ("THE ASSIGNMENT", "HOW — the baseline approach",
                   "YOUR ALTERNATIVE", "HARD RULES", "WHAT TO DELIVER",
                   "PART 1-4", "PART 5", "PART 6", "PART 7", "REVIEW FIX 01",
                   "APPENDIX A", "APPENDIX B"):
        if marker not in text:
            raise SystemExit(f"ASSEMBLY FAILED — missing section: {marker}")
    print("all sections present")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
