#!/usr/bin/env python3
"""Export the ENTIRE project record into portable files another AI can read.

Founder directive, 2026-07-26: "I need you to pull together every file, all
conversations and instruction from every session, put them into files. And I
need a link to all of that so I can provide it to other AI."

Honest scope, stated up front because the difference matters: raw CHAT
transcripts from other sessions are not on disk and this tool cannot invent
them. What IS on disk is the durable record those sessions were required to
write — session contracts, decision records with founder verbatims, session
arcs, the change log, the Kaizen ledger, the deferral Record, and the standing
instructions. That is the corpus. Where a session's reasoning exists only in a
chat window it was never captured, and this export says so rather than implying
completeness it does not have.

Outputs (docs/export/):
  ONELIVE_CONTEXT_INDEX.md   a map: what each file is and why it matters
  ONELIVE_FULL_CONTEXT.md    everything concatenated, delimited per file
  ONELIVE_INSTRUCTIONS.md    the standing rules only (smaller, for a fresh AI)
"""
from __future__ import annotations

import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
OUT = REPO / "docs" / "export"

# Ordered so a reader meets the project the way a new session must: what the
# rules are, then where things stand, then how they got there.
SECTIONS: list = [
    ("STANDING INSTRUCTIONS — read these first; they are the contract", [
        "CLAUDE.md",
        "docs/OPERATING_RULES.md",
        "docs/SESSION_START.md",
        "docs/CODING_CONVENTIONS.md",
        "docs/KAIZEN.md",
        "docs/WORLD_CLASS.md",
        "docs/MODEL_ROUTING.md",
    ]),
    ("CURRENT STATE — what is true now", [
        "STATE.md",
        "TODOS.md",
        "docs/RECORD.md",
        "LIVE_READINESS.md",
        "docs/GO_LIVE_PLAN.md",
    ]),
    ("FOUNDER DECISIONS — verbatim directives, the authority for everything", [
        "docs/memory/decisions",
    ]),
    ("HARD-WON LESSONS — failure classes and gotchas", [
        "docs/memory/RED_CLASSES.md",
        "docs/memory/gotchas",
        "docs/memory/README.md",
    ]),
    ("SESSION HISTORY — how we got here", [
        "docs/session_arcs",
        "docs/ops",
        "docs/ONE_LIVE_CHANGE_LOG.md",
    ]),
    ("MEASUREMENT — the ledgers", [
        "docs/metrics",
    ]),
    ("SPECIFICATION + DESIGN CANON", [
        "docs/Final_ONE_Live_Authoritative_Technical_Spec.md",
        "docs/design",
        "docs/strategy",
    ]),
    ("PROCESS — skills, hats, review personas", [
        "docs/skills",
        "docs/hats",
        "docs/review_personas",
    ]),
]

INSTRUCTION_ONLY = [
    "CLAUDE.md",
    "docs/OPERATING_RULES.md",
    "docs/SESSION_START.md",
    "docs/memory/RED_CLASSES.md",
    "docs/GO_LIVE_PLAN.md",
]


def _files_for(entry: str) -> list:
    path = REPO / entry
    if path.is_dir():
        return sorted(p for p in path.rglob("*.md") if p.is_file())
    return [path] if path.is_file() else []


def _emit(paths: list, title: str) -> tuple:
    """Concatenate `paths` with explicit delimiters. Returns (text, missing)."""
    chunks = [f"# {title}\n"]
    missing: list = []
    for p in paths:
        rel = p.relative_to(REPO)
        try:
            body = p.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError) as exc:
            missing.append(f"{rel} ({exc})")
            continue
        chunks.append(
            f"\n\n{'=' * 78}\n===== FILE: {rel}\n{'=' * 78}\n\n{body}")
    return "".join(chunks), missing


def main(argv=None) -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    index: list = [
        "# OneLive — context export index",
        "",
        "Generated by `tools/export_context.py`. Regenerate after any session.",
        "",
        "## What this export IS",
        "",
        "The complete on-disk record of the OneLive project: the standing rules,",
        "the current state, every founder decision recorded verbatim, the failure",
        "classes learned the hard way, the per-session arcs, the ledgers, and the",
        "specification and design canon.",
        "",
        "## What this export is NOT",
        "",
        "It is **not** raw chat transcripts. Conversations from prior sessions were",
        "never stored as files — what survives is what each session was required to",
        "write down: contracts, decision records (with the founder's words quoted",
        "verbatim), arcs, and ledgers. Where a session's reasoning lived only in a",
        "chat window, it is gone, and this export does not pretend otherwise.",
        "",
        "## Files",
        "",
        "| File | Use it for |",
        "|---|---|",
        "| `ONELIVE_INSTRUCTIONS.md` | Hand to a fresh AI first. The rules only — small enough to fit any context. |",
        "| `ONELIVE_FULL_CONTEXT.md` | Everything. Large; use when the AI has a big context window or can chunk. |",
        "| `ONELIVE_CONTEXT_INDEX.md` | This file — the map. |",
        "",
        "## Contents of the full export, in reading order",
        "",
    ]

    all_chunks: list = []
    all_missing: list = []
    total_files = 0
    for title, entries in SECTIONS:
        paths: list = []
        for e in entries:
            paths.extend(_files_for(e))
        if not paths:
            continue
        total_files += len(paths)
        index.append(f"### {title}")
        index.append("")
        for p in paths:
            index.append(f"- `{p.relative_to(REPO)}`")
        index.append("")
        text, missing = _emit(paths, title)
        all_chunks.append(text)
        all_missing.extend(missing)

    full = "\n\n\n".join(all_chunks)
    (OUT / "ONELIVE_FULL_CONTEXT.md").write_text(full, encoding="utf-8")

    inst_paths: list = []
    for e in INSTRUCTION_ONLY:
        inst_paths.extend(_files_for(e))
    inst, _ = _emit(inst_paths, "OneLive — standing instructions for a new AI")
    (OUT / "ONELIVE_INSTRUCTIONS.md").write_text(inst, encoding="utf-8")

    index.append("## Generation report")
    index.append("")
    index.append(f"- files exported: **{total_files}**")
    index.append(f"- full export size: **{len(full):,} characters**")
    index.append(f"- instructions-only size: **{len(inst):,} characters**")
    if all_missing:
        index.append(f"- UNREADABLE (named, never silently dropped): {all_missing}")
    else:
        index.append("- unreadable files: none")
    (OUT / "ONELIVE_CONTEXT_INDEX.md").write_text(
        "\n".join(index) + "\n", encoding="utf-8")

    print(f"export_context: {total_files} files -> {OUT}")
    print(f"  ONELIVE_FULL_CONTEXT.md   {len(full):,} chars")
    print(f"  ONELIVE_INSTRUCTIONS.md   {len(inst):,} chars")
    if all_missing:
        print(f"  UNREADABLE: {all_missing}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
