#!/usr/bin/env python3
"""Generate web/lib/tasting_venues.generated.ts from the source catalog.

The Tasting Trail section (docs/design/TASTING_TRAIL_SECTION_v1.md) shows
breweries / wineries / distilleries as an ALWAYS-ON venue directory — visible
even when a venue has no scheduled event. Those venues live in the curated,
first-party source catalog (cultural_domain=food-drink, entity_type=venue,
policy-railed). This generator extracts them into a typed, web-bundled data
file so the Next.js section renders the directory WITHOUT a DB migration; a
venue's live events still join from the pipeline when present (never fabricated).

Truth-first: this file carries ONLY venue-identity fields the catalog already
records (name, kind, county, first-party url) — no event claims.

Run:
  python tools/gen_tasting_venues.py           # (re)write the generated file
  python tools/gen_tasting_venues.py --check    # exit 1 if the file is stale

A sync test (tests/test_gen_tasting_venues.py) keeps the generated file from
drifting from the catalog.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
CATALOG = ROOT / "sources" / "master_sources_catalog_120.json"
OUT = ROOT / "web" / "lib" / "tasting_venues.generated.ts"

# Valid kinds — kept in sync with web/lib/venues.ts TastingKind.
VALID_KINDS = ("winery", "brewery", "distillery", "beer-garden", "restaurant", "tasting-room")


def derive_kind(text: str) -> str:
    """Classify a tasting venue by keyword. Order matters: distillery and
    beer-garden are checked before the broader brewery/winery/restaurant
    keywords so e.g. a 'Beer Garden & Grille' is a beer-garden, not a
    restaurant, and a 'Whiskey Co.' is a distillery."""
    t = text.lower()
    if any(k in t for k in ("distill", "whiskey", "whisky", "bourbon", "spirits", "speakeasy")):
        return "distillery"
    if "beer garden" in t or "biergarten" in t:
        return "beer-garden"
    if any(k in t for k in ("brewery", "brewing", "beerworks", "brewpub")):
        return "brewery"
    if any(k in t for k in ("winery", "vineyard", "cellars", "wine")):
        return "winery"
    if any(k in t for k in ("restaurant", "grille", "steakhouse", "saloon", "kitchen", "grill")):
        return "restaurant"
    return "tasting-room"


def build_venues() -> list[dict]:
    """The food-drink venues from the catalog, mapped to directory records and
    sorted deterministically (county, then name) so the generated file is
    stable across runs."""
    cat = json.loads(CATALOG.read_text(encoding="utf-8"))
    out = []
    for e in cat:
        if e.get("cultural_domain") != "food-drink" or e.get("entity_type") != "venue":
            continue
        name = e.get("name") or ""
        notes = e.get("notes") or ""
        out.append({
            "id": str(e.get("id")),
            "name": name,
            "kind": derive_kind(f"{name} {notes}"),
            "county": str(e.get("county") or "").lower(),
            "url": e.get("base_url") or "",
        })
    out.sort(key=lambda v: (v["county"], v["name"].lower()))
    return out


def render(venues: list[dict]) -> str:
    lines = [
        "// GENERATED by tools/gen_tasting_venues.py — DO NOT EDIT BY HAND.",
        "// Source: sources/master_sources_catalog_120.json"
        " (cultural_domain=food-drink, entity_type=venue).",
        "// Regenerate: python tools/gen_tasting_venues.py"
        " (a sync test enforces this stays current).",
        'import type { TastingVenue } from "./venues";',
        "",
        "export const TASTING_VENUES: TastingVenue[] = [",
    ]
    for v in venues:
        lines.append(
            "  { "
            f'id: {json.dumps(v["id"])}, '
            f'name: {json.dumps(v["name"], ensure_ascii=False)}, '
            f'kind: {json.dumps(v["kind"])}, '
            f'county: {json.dumps(v["county"])}, '
            f'url: {json.dumps(v["url"])} '
            "},"
        )
    lines.append("];")
    lines.append("")
    return "\n".join(lines)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Generate the Tasting Trail venue directory.")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the generated file is out of date (CI/sync guard)")
    args = ap.parse_args(argv)

    venues = build_venues()
    content = render(venues)

    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != content:
            print("tasting_venues.generated.ts is OUT OF DATE — run: "
                  "python tools/gen_tasting_venues.py", file=sys.stderr)
            return 1
        print(f"tasting_venues.generated.ts is in sync ({len(venues)} venues)")
        return 0

    OUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} with {len(venues)} tasting venues")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
